version: "3"

services:
  postgres:
    image: "postgres:14.3"
    hostname: file_system_clicksign_db
    container_name: file_system_clicksign_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    depends_on:
      - "postgres"
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/file_system_clicksign
      - gems:/gems

volumes:
  postgres:
  gems: